[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixpkgs = ["nodejs_22"]

[phases.build]
cmds = ["pnpm exec prisma generate", "pnpm run build"]

[phases.start]
cmds = ["pnpm exec prisma migrate deploy", "pnpm run start"]
